export { AuthStep } from './AuthStep'
export { ContactStep, type ContactData } from './ContactStep'
export { StudentStep, type StudentData } from './StudentStep'
export { ConfirmationStep, type BookingData } from './ConfirmationStep'
export { SuccessStep } from './SuccessStep'